[notebook]
dir = "~/DATA/02_Informational/Zettelkasten/Notebook"

[note]
language = "en"

filename = "{{id}}-{{slug title}}"

id-charset = "alphanum"
id-length = 10
id-case = "lower"

[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]

edlast = "zk edit --limit 1 --sort modified- $argv"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

ls = "zk edit --interactive -x journal"
t = "zk edit --interactive --tag $argv"

conf = '$EDITOR "$HOME/.config/zk/config.toml"'

daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/daily"'
journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"

ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title $argv'

inline = "zk list --quiet --format {{path}} --delimiter , $argv"

flimsy = "zk list --format '{{word-count}}\t{{title}}' --sort word-count --limit 20"

projects = "zk edit $ZK_NOTEBOOK_DIR/projects.md"


# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "none"
# Warn for dead links between notes.
dead-link = "error"
